# Generated by Django 4.1.7 on 2023-06-14 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RiderName', models.CharField(max_length=200)),
                ('RiderBMI', models.IntegerField()),
                ('RiderMass', models.IntegerField()),
                ('RiderAcceleration', models.IntegerField()),
                ('RiderAppliedForce', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Prediction_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RiderName', models.CharField(max_length=200)),
                ('RiderAppliedForce', models.IntegerField()),
                ('RiderPredictedForce', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RiderName', models.CharField(max_length=200)),
                ('RiderMail', models.CharField(max_length=50)),
                ('RiderHeight', models.IntegerField()),
                ('RiderWeight', models.IntegerField()),
                ('RiderBMI', models.IntegerField()),
                ('RiderMass', models.IntegerField()),
            ],
        ),
    ]
