# Generated by Django 4.1.7 on 2023-06-14 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='RiderAcceleration',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='features',
            name='RiderAppliedForce',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='features',
            name='RiderBMI',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='features',
            name='RiderMass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prediction_output',
            name='RiderAppliedForce',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='prediction_output',
            name='RiderPredictedForce',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rider',
            name='RiderBMI',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rider',
            name='RiderHeight',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rider',
            name='RiderMass',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rider',
            name='RiderWeight',
            field=models.FloatField(),
        ),
    ]
